export const languages = [
    { id: 'en', name: 'English', flag: '/assets/uk.png' },
    { id: 'ka', name: 'Georgian', flag: '/assets/ge.png' }
]

export const languageData = {
    en: {
        sign_up: 'Sign up',
        log_in: 'Log in',
        log_out: 'Log out',
        price: 'Prices starting from',
        reviews: 'Reviews',
        footer_main_text: 'Hotel platform created for Scripting Languages',
        contact: 'Contact',
        show_searchbox: 'Show searchbox',
        hide_searchbox: 'Hide searchbox',
        sorting_option_none: 'Select a sorting option',
        sorting_option_az: 'By name: A-Z',
        sorting_option_za: 'By name: Z-A',
        sorting_option_priceasc: 'By price: low to high',
        sorting_option_pricedesc: 'By price: high to low',
        sorting_option_ratingasc: 'By rating: low to high',
        sorting_option_ratingdesc: 'By rating: high to low',
        searchbar_placeholder: 'Search by name...',
        filter_price: 'Filter by price',
        filter_rating: 'Filter by rating',
        min: 'Min',
        max: 'Max',
        search: 'Search',
        email: 'Email',
        password: 'Password',
        email_username: 'Email or Username',
    },
    ka: {
        sign_up: 'რეგისტრაცია',
        log_in: 'შესვლა',
        log_out: 'გასვლა',
        price: 'ფასი',
        reviews: 'განხილვა',
        footer_main_text: 'სასტუმროების პლატფორმა, შექმნილია Scripting Languages ფინალური პროექტისთვის',
        contact: 'კონტაქტი',
        show_searchbox: 'აჩვენე საძიებო ველები',
        hide_searchbox: 'დამალე საძიებო ველები',
        sorting_option_none: 'სორტირება',
        sorting_option_az: 'დასახელება: A-Z',
        sorting_option_za: 'დასახელება: Z-A',
        sorting_option_priceasc: 'ფასი: ზრდადობით',
        sorting_option_pricedesc: 'ფასი: კლებადობით',
        sorting_option_ratingasc: 'რეიტინგი: ზრდადობით',
        sorting_option_ratingdesc: 'რეიტინგი: კლებადობით',
        searchbar_placeholder: 'მოძებნე სახელით...',
        filter_price: 'გაფილტვრა ფასით',
        filter_rating: 'გაფილტვრა რეიტინგით',
        min: 'დან',
        max: 'მდე',
        search: 'ძებნა',
        email: 'ელფოსტა',
        password: 'პაროლი',
        email_username: 'ელფოსტა',
    }
}